<?php
/**
 * Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

$fibonachi_last = 3;
$fibonachi_1st_to_last = 2;
$answer = 2;

while ($fibonachi_last <= 4000000) {
	$fibonachi_last_before = $fibonachi_last;
	$fibonachi_last = $fibonachi_last_before + $fibonachi_1st_to_last;
	$fibonachi_1st_to_last = $fibonachi_last_before;

	if ($fibonachi_last % 2 == 0) {
		$answer += $fibonachi_last;
	}
}

echo $answer;